version: "3.8"
services:
  superset:
    image: apache/superset:latest
    container_name: superset
    env_file: .env
    ports:
      - "8088:8088"
    depends_on:
      - redis
    volumes:
      - ./superset:/app/superset_home
      - ./app/pythonpath/superset_config.py:/app/pythonpath/superset_config.py
    command:
      - /bin/sh
      - -c
      - |
        superset db upgrade && \
        superset init && \
        superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger
      
  
  redis:
    image: redis:latest
    container_name: superset_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
