version: "3.8"
services:
  db:
    image: postgres:12
    container_name: superset_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/init_superset_db.sh:/docker-entrypoint-initdb.d/init_superset_db.sh
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
