version: "3.8"

services:

  superset:
    image: apache/superset:latest
    container_name: superset
    env_file: ./.env
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: ['/bin/sh' , '-c', 'bootstrap-dev.sh']
  
  db:
    image: postgres:12
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: superset_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  superset_home:
  postgres_data:
  redis_data:
